import { Injectable } from "@nestjs/common"; import { monthRange, today } from "../common/date"; import { GoalType, TargetType } from "../common/enums"; import { GoalsService } from "../goals/goals.service"; import { TransactionsService } from "../transactions/transactions.service"; import { WorkDaysService } from "../work-days/work-days.service";
const fmt = (value: number) => `${new Intl.NumberFormat("vi-VN").format(value)}đ`;
@Injectable()
export class ReportsService {
  constructor(private readonly transactions: TransactionsService, private readonly workDays: WorkDaysService, private readonly goals: GoalsService) {}
  async daily(userId: string, date = today()) { const t = await this.transactions.totals(userId, date, date); const work = await this.workDays.findForDay(userId, date); return `📋 DAILY SUMMARY\n${date}\n\n💰 Thu nhập: +${fmt(t.income)}\n💸 Chi tiêu: -${fmt(t.expense)}\n💵 Net: ${t.saving >= 0 ? "+" : ""}${fmt(t.saving)}\n\n💼 Đi làm: ${work?.type ?? "Chưa đánh dấu"}`; }
  async monthly(userId: string, referenceDate = today()) { const range = monthRange(referenceDate); const totals = await this.transactions.totals(userId, range.start, range.end); const worked = await this.workDays.countWorked(userId, range.start, range.end); const goals = await this.goals.active(userId, referenceDate); const lines = goals.map((goal) => { const actual = goal.type === GoalType.INCOME ? totals.income : goal.type === GoalType.EXPENSE ? totals.expense : goal.type === GoalType.SAVING ? totals.saving : worked; const target = Number(goal.targetValue); const done = goal.targetType === TargetType.MIN ? actual >= target : goal.targetType === TargetType.MAX ? actual <= target : actual === target; return `${goal.name}: ${goal.type === GoalType.WORK_DAYS ? actual : fmt(actual)} / ${goal.type === GoalType.WORK_DAYS ? target : fmt(target)} ${done ? "✅" : "❌"}`; }); return `📊 MONTHLY REPORT — ${range.label}\n\n💰 Thu nhập: ${fmt(totals.income)}\n💸 Chi tiêu: ${fmt(totals.expense)}\n💵 Tiết kiệm: ${fmt(totals.saving)}\n💼 Đi làm: ${worked} ngày\n\n🎯 GOALS\n${lines.length ? lines.join("\n") : "Chưa có mục tiêu"}`; }
  async range(userId: string, from: string, to: string) { const totals = await this.transactions.totals(userId, from, to); const worked = await this.workDays.countWorked(userId, from, to); const days = Math.max(1, Math.floor((Date.parse(`${to}T00:00:00Z`) - Date.parse(`${from}T00:00:00Z`)) / 86400000) + 1); return `📊 REPORT\n${from} → ${to}\n\n💰 Income: ${fmt(totals.income)}\n💸 Expense: ${fmt(totals.expense)}\n💵 Saving: ${fmt(totals.saving)}\n💼 Work: ${worked} ngày\n\n📈 Daily average\nIncome: ${fmt(Math.round(totals.income / days))}\nExpense: ${fmt(Math.round(totals.expense / days))}\nSaving: ${fmt(Math.round(totals.saving / days))}`; }
  async weekly(userId: string, date = today()) { const d = new Date(`${date}T00:00:00Z`); const day = d.getUTCDay() || 7; d.setUTCDate(d.getUTCDate() - day + 1); const from = d.toISOString().slice(0, 10); d.setUTCDate(d.getUTCDate() + 6); return this.range(userId, from, d.toISOString().slice(0, 10)); }
}
